server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC


  mail:
    host: smtp.gmail.com
    port: 587
    username: aida.cherkezova@gmail.com
    password:   waeutqtjuvgwwgpb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis
    ttl-seconds: 100

  data:
    redis:
      host: localhost
      port: 6379

  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    org.springframework: INFO
    com.ticketsystem: DEBUG

jwt:
  secret: zkUL+Jz3WKgMDZgAD6rh9a4VvKye6NgKUtnld4cdF9Mbp7FdIOJfI5y5Y96l1n8H6w2iLfZfYngBvA1EBhHXpA==


