server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:onlineticket_db
    username: sa
    password:

  # Uncomment below to switch to PostgreSQL
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/ticket_db
  #    username: postgres
  #    password: 12345
  #    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  # Uncomment below if using PostgreSQL
  #        dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis
    ttl-seconds: 100

  data:
    redis:
      host: localhost
      port: 6379

  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    org.springframework: INFO
    com.ticketsystem: DEBUG
